
export const COMMUNNES = [
    { value: 'ALHUÉ', viewValue: 'Alhué' },
    { value: 'BUIN', viewValue: 'Buin' },
    { value: 'CALERA_DE_TANGO', viewValue: 'Calera De Tango' },
    { value: 'CERRILLOS', viewValue: 'Cerrillos' },
    { value: 'CERRO_NAVIA', viewValue: 'Cerro Navia' },
    { value: 'COLINA', viewValue: 'Colina' },
    { value: 'CONCHALÍ', viewValue: 'Conchalí' },
    { value: 'CURACAVÍ', viewValue: 'Curacaví' },
    { value: 'EL_BOSQUE', viewValue: 'El Bosque' },
    { value: 'EL_MONTE', viewValue: 'El Monte' },
    { value: 'ESTACIÓN_CENTRAL', viewValue: 'Estación Central' },
    { value: 'HUECHURABA', viewValue: 'Huechuraba' },
    { value: 'INDEPENDENCIA', viewValue: 'Independencia' },
    { value: 'ISLA_DE_MAIPO', viewValue: 'Isla De Maipo' },
    { value: 'LA_CISTERNA', viewValue: 'La Cisterna' },
    { value: 'LA_FLORIDA', viewValue: 'La Florida' },
    { value: 'LA_GRANJA', viewValue: 'La Granja' },
    { value: 'LA_PINTANA', viewValue: 'La Pintana' },
    { value: 'LA_REINA', viewValue: 'La Reina' },
    { value: 'LAMPA', viewValue: 'Lampa' },
    { value: 'LAS_CONDES', viewValue: 'Las Condes' },
    { value: 'LO_BARNECHEA', viewValue: 'Lo Barnechea' },
    { value: 'LO_ESPEJO', viewValue: 'Lo Espejo' },
    { value: 'LO_PRADO', viewValue: 'Lo Prado' },
    { value: 'MACUL', viewValue: 'Macul' },
    { value: 'MAIPÚ', viewValue: 'Maipú' },
    { value: 'MARÍA_PINTO', viewValue: 'María Pinto' },
    { value: 'MELIPILLA', viewValue: 'Melipilla' },
    { value: 'ÑUÑOA', viewValue: 'Ñuñoa' },
    { value: 'PADRE_HURTADO', viewValue: 'Padre Hurtado' },
    { value: 'PAINE', viewValue: 'Paine' },
    { value: 'PEDRO_AGUIRRE_CERDA', viewValue: 'Pedro Aguirre Cerda' },
    { value: 'PEÑAFLOR', viewValue: 'Peñaflor' },
    { value: 'PEÑALOLÉN', viewValue: 'Peñalolén' },
    { value: 'PIRQUE', viewValue: 'Pirque' },
    { value: 'PROVIDENCIA', viewValue: 'Providencia' },
    { value: 'PUDAHUEL', viewValue: 'Pudahuel' },
    { value: 'PUENTE_ALTO', viewValue: 'Puente Alto' },
    { value: 'QUILICURA', viewValue: 'Quilicura' },
    { value: 'QUINTA_NORMAL', viewValue: 'Quinta Normal' },
    { value: 'RECOLETA', viewValue: 'Recoleta' },
    { value: 'RENCA', viewValue: 'Renca' },
    { value: 'SAN_BERNARDO', viewValue: 'San Bernardo' },
    { value: 'SAN_JOAQUÍN', viewValue: 'San Joaquín' },
    { value: 'SAN_JOSÉ_DE_MAIPO', viewValue: 'San José De Maipo' },
    { value: 'SAN_MIGUEL', viewValue: 'San Miguel' },
    { value: 'SAN_PEDRO', viewValue: 'San Pedro' },
    { value: 'SAN_RAMÓN', viewValue: 'San Ramón' },
    { value: 'SANTIAGO', viewValue: 'Santiago' },
    { value: 'TALAGANTE', viewValue: 'Talagante' },
    { value: 'TILTIL', viewValue: 'Tiltil' },
    { value: 'VITACURA', viewValue: 'Vitacura' }
];