import { Theme } from "./theme";

export const THEMESLIGHT: Theme[] = [
    { name: 'purple-pink', primaryColor: '#9c27b0', accentColor: '#ff4081', dark: false },
    { name: 'deeppurple-amber', primaryColor: '#673ab7', accentColor: '#ffab00', dark: false },
    { name: 'indigo-pink', primaryColor: '#3F51B5', accentColor: '#ff4081', dark: false },
    { name: 'indigo-lightblue', primaryColor: '#3f51b5', accentColor: '#03a9f4', dark: false },
    { name: 'indigo-orange', primaryColor: '#3f51b5', accentColor: '#ef6c00', dark: false },
    { name: 'blue-orange', primaryColor: '#2979ff', accentColor: '#ffab40', dark: false },
    { name: 'lightblue-purple', primaryColor: '#03a9f4', accentColor: '#d500f9', dark: false },
    { name: 'cyan-indigo', primaryColor: '#00bcd4', accentColor: '#536dfe', dark: false },
    { name: 'teal-orange', primaryColor: '#00897b', accentColor: '#ff9800', dark: false },
    { name: 'green-purple', primaryColor: '#43a047', accentColor: '#d500f9', dark: false },
    { name: 'lightgreen-blue', primaryColor: '#7cb342', accentColor: '#448aff', dark: false },
    { name: 'lime-pink', primaryColor: '#c0ca33', accentColor: '#ff4081', dark: false },
    { name: 'yellow-deeppurple', primaryColor: '#fbc02d', accentColor: '#7c4dff', dark: false },
    { name: 'amber-blue', primaryColor: '#ffa000', accentColor: '#2962ff', dark: false },
    { name: 'orange-indigo', primaryColor: '#ef6c00', accentColor: '#536dfe', dark: false },
    //{ name: 'grey-lightblue', primaryColor: '#757575', accentColor: '#03a9f4', dark: false },
    { name: 'bluegrey-amber', primaryColor: '#607d8b', accentColor: '#ffab00', dark: false },
    { name: 'bluegrey-lightblue', primaryColor: '#607d8b', accentColor: '#40c4ff', dark: false },
    { name: 'brown-orange', primaryColor: '#795548', accentColor: '#ef6c00', dark: false },
];

export const THEMESDARK: Theme[] = [
    { name: 'purple-pink-dark', primaryColor: '#aa00ff', accentColor: '#ff4081', dark: true },
    { name: 'deeppurple-amber-dark', primaryColor: '#7c4dff', accentColor: '#ffab00', dark: true },
    { name: 'indigo-pink-dark', primaryColor: '#3d5afe', accentColor: '#ff4081', dark: true },
    { name: 'indigo-lightblue-dark', primaryColor: '#304ffe', accentColor: '#03a9f4', dark: true },
    { name: 'indigo-orange-dark', primaryColor: '#304ffe', accentColor: '#ef6c00', dark: true },
    { name: 'blue-orange-dark', primaryColor: '#448aff', accentColor: '#ffab40', dark: true },
    { name: 'lightblue-purple-dark', primaryColor: '#00b0ff', accentColor: '#d500f9', dark: true },
    { name: 'cyan-indigo-dark', primaryColor: '#00bcd4', accentColor: '#536dfe', dark: true },
    { name: 'teal-orange-dark', primaryColor: '#009688', accentColor: '#ff9800', dark: true },
    { name: 'green-purple-dark', primaryColor: '#4caf50', accentColor: '#d500f9', dark: true },
    { name: 'lightgreen-blue-dark', primaryColor: '#8bc34a', accentColor: '#448aff', dark: true },
    { name: 'lime-pink-dark', primaryColor: '#CDDC39', accentColor: '#ff4081', dark: true },
    { name: 'yellow-deeppurple-dark', primaryColor: '#fbc02d', accentColor: '#7c4dff', dark: true },
    { name: 'amber-blue-dark', primaryColor: '#ffa000', accentColor: '#2962ff', dark: true },
    { name: 'orange-indigo-dark', primaryColor: '#ef6c00', accentColor: '#536dfe', dark: true },
    //{ name: 'grey-lightblue-dark', primaryColor: '#9e9e9e', accentColor: '#03a9f4', dark: true },
    { name: 'bluegrey-amber-dark', primaryColor: '#78909c', accentColor: '#ffab00', dark: true },
    { name: 'bluegrey-lightblue-dark', primaryColor: '#78909c', accentColor: '#40c4ff', dark: true },
    { name: 'brown-orange-dark', primaryColor: '#8d6e63', accentColor: '#ef6c00', dark: true },
];